name: CI for LABWORK2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GCC
        run: sudo apt update && sudo apt install -y g++ make cmake

      - name: install Google Test
        run: |
          sudo apt-get install -y libgtest-dev libgmock-dev make

      - name: Build with Makefile
        run: make
